const PAGES=[['dashboard','📊 Dashboard'],['partite','⚽ Partite'],['classifica','🏆 Classifica'],['pagella','🏅 Pagella'],['ricordi','📸 Ricordi'],['scheda','🪪 Scheda Giocatore'],['giocatori','👤 Giocatori'],['regolamento','📜 Regolamento'],['luogo','📍 Luogo'],['settings','⚙️ Settings']];
const ROLES=['Portiere','Difensore','Centrocampista','Attaccante'];
const KEY='calcetto-manager-2026-27-v2';
const NAMES=['Alberto','Alex Car.','Carlo','Cyr','Daniele','Fausto','Gabriele','Giovanni','Giulio','Loris','Matteo','Max','Mirko','Roberto','Tommaso','Lorenzo'];
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function initial(){return {version:2,season:'2026/27',players:NAMES.map((name,i)=>({id:'p'+i,name,role:ROLES[i%4],registration:true,team:'',secondTeam:false,admissionFee:0,paid:false,injured:false,status:'Attivo',referee:false,baseAverage:0,baseGoals:0,baseAssists:0,baseAppearances:0})),matches:[],ratings:[],memories:[],rules:'',place:'Via Carreggia, 21010 Cardano al Campo VA',settings:{dark:false,debug:false,pagella:true}}}
let db=JSON.parse(localStorage.getItem(KEY)||'null')||initial();
function save(){localStorage.setItem(KEY,JSON.stringify(db))} save();
const nav=document.getElementById('nav'),app=document.getElementById('app');
function go(id){history.pushState({},'',`#${id}`);render(id)}
window.onpopstate=()=>render(location.hash.slice(1)||'dashboard');
function renderNav(a){nav.innerHTML=PAGES.map(([id,l])=>`<button class="${id===a?'active':''}" onclick="go('${id}')">${l}</button>`).join('')}
function layout(t,b){return `<div class="wrap"><div class="page-title"><div><div class="eyebrow">CALCETTO MANAGER</div><h1>${t}</h1></div><span class="season">${esc(db.season)}</span></div>${b}</div>`}
function render(id){renderNav(id);document.body.classList.toggle('dark',!!db.settings.dark);({dashboard,partite,classifica,pagella,ricordi,scheda,giocatori,regolamento,luogo,settings}[id]||dashboard)()}
function allStats(){const s={};db.players.forEach(p=>s[p.id]={p,g:0,a:0,y:0,r:0,og:0,pen:0,sub:0,change:0,app:0});db.matches.forEach(m=>m.players.forEach(x=>{const z=s[x.id];if(!z)return;z.app++;z.g+=+x.g||0;z.a+=+x.a||0;z.y+=+x.y||0;z.r+=+x.r||0;z.og+=+x.og||0;z.pen+=+x.pen||0;z.sub+=+x.sub||0;z.change+=x.change?1:0}));return Object.values(s)}
function dashboard(){const s=allStats(),goals=s.reduce((n,x)=>n+x.g,0),cards=s.reduce((n,x)=>n+x.y+x.r,0),last=db.matches.at(-1),top=[...s].sort((a,b)=>b.g-a.g||b.a-a.a)[0];app.innerHTML=layout('PANORAMICA',`<div class="toolbar"><span>Stagione <b>${esc(db.season)}</b></span><button class="btn" onclick="render('dashboard')">↻ Aggiorna</button></div><div class="cards"><div class="stat"><b>${db.matches.length}</b><span>Partite</span></div><div class="stat"><b>${db.players.filter(p=>p.status==='Attivo').length}</b><span>Giocatori attivi</span></div><div class="stat"><b>${goals}</b><span>Gol totali</span></div><div class="stat"><b>${cards}</b><span>Cartellini</span></div></div><div class="grid2 dashboard-grid"><div class="panel"><h2>⚽ Ultima partita</h2>${last?matchPreview(last):'<div class="empty">Nessuna partita registrata.</div>'}</div><div class="panel"><h2>🏅 TOP SCORER</h2>${top&&top.g?`<div class="big-number">${top.g}</div><b>${esc(top.p.name)}</b>`:'<div class="empty">Nessun dato.</div>'}</div></div><div class="panel"><div class="toolbar"><h2>STATISTICHE STAGIONE</h2><button class="btn" onclick="go('classifica')">Classifica completa →</button></div>${statsTable(s.slice().sort((a,b)=>b.g-a.g||b.a-a.a))}</div>`)}
function statsTable(s){return `<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Nome</th><th>Ruolo</th><th>Partite</th><th>Gol</th><th>Assist</th><th>Cart.</th><th>Aut.</th><th>Rig.</th><th>Subiti</th><th>Cambio</th></tr></thead><tbody>${s.map((x,i)=>`<tr onclick="goPlayer('${x.p.id}')"><td>${i+1}</td><td><b>${esc(x.p.name)}</b></td><td><span class="badge">${esc(x.p.role)}</span></td><td>${x.app}</td><td>${x.g}</td><td>${x.a}</td><td>${x.y+x.r}</td><td>${x.og}</td><td>${x.pen}</td><td>${x.sub}</td><td>${x.change}</td></tr>`).join('')}</tbody></table></div>`}
function matchPreview(m){return `<div class="match-preview"><div><strong>🇮🇹 SQUADRA A</strong><span>${m.players.filter(x=>x.team==='A').map(x=>esc(x.name)).join(' · ')||'—'}</span></div><div class="score">${m.scoreA} <small>–</small> ${m.scoreB}<em>${esc(m.date)} · ${esc(m.format)}</em></div><div><strong>🇧🇷 SQUADRA B</strong><span>${m.players.filter(x=>x.team==='B').map(x=>esc(x.name)).join(' · ')||'—'}</span></div></div><button class="btn primary" onclick="openMatch('${m.id}')">Dettaglio partita</button>`}
function partite(){app.innerHTML=layout('PARTITE',`<div class="toolbar"><span><b>${db.matches.length}</b> partite registrate</span><button class="btn primary" onclick="newMatchForm()">＋ Nuova partita</button></div>${db.matches.slice().reverse().map(m=>`<div class="panel match-row">${matchPreview(m)}<button class="btn danger" onclick="deleteMatch('${m.id}')">Elimina</button></div>`).join('')||'<div class="panel empty">Nessuna partita. Crea la prima partita della stagione.</div>'}`)}
function newMatchForm(){app.innerHTML=layout('NUOVA PARTITA',`<form class="panel form" onsubmit="createMatch(event)"><div class="form-grid"><label>Data<input id="mdate" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Formato<select id="mformat"><option>6 VS 6</option><option>5 VS 5</option><option>7 VS 7</option><option>8 VS 8</option><option>Altro</option></select></label><label>Arbitro<input id="mref" placeholder="Nome arbitro"></label><label>Stato<select id="mplayed"><option value="true">Disputata</option><option value="false">Da disputare</option></select></label></div><div class="score-input"><label>Squadra A<input id="sa" type="number" min="0" value="0" required></label><b>–</b><label>Squadra B<input id="sb" type="number" min="0" value="0" required></label></div><h2>Giocatori</h2><p class="muted">Seleziona la squadra di ogni giocatore. I giocatori non selezionati non risultano presenti.</p><div class="player-pick">${db.players.filter(p=>p.status!=='Inattivo').map(p=>`<div class="pick"><b>${esc(p.name)}</b><select data-pid="${p.id}"><option value="">—</option><option value="A">🇮🇹 A</option><option value="B">🇧🇷 B</option></select></div>`).join('')}</div><div class="toolbar"><button type="button" class="btn" onclick="go('partite')">Annulla</button><button class="btn primary">💾 Salva partita</button></div></form>`)}
function createMatch(e){e.preventDefault();const players=[...document.querySelectorAll('[data-pid]')].map(sel=>{if(!sel.value)return null;const p=db.players.find(x=>x.id===sel.dataset.pid);return{id:p.id,name:p.name,team:sel.value,g:0,a:0,y:0,r:0,og:0,pen:0,sub:0,change:false}}).filter(Boolean);db.matches.push({id:uid('m'),date:document.getElementById('mdate').value,format:document.getElementById('mformat').value,referee:document.getElementById('mref').value,played:document.getElementById('mplayed').value==='true',scoreA:+document.getElementById('sa').value,scoreB:+document.getElementById('sb').value,players,notes:''});save();go('partite')}
function openMatch(id){const m=db.matches.find(x=>x.id===id);if(!m)return;app.innerHTML=layout('DETTAGLIO PARTITA',`<div class="panel match-head"><div><span class="muted">${esc(m.date)}</span><h2>${esc(m.format)}</h2><span>${m.played?'CONCLUSA':'DA DISPUTARE'}${m.referee?' · Arbitro: '+esc(m.referee):''}</span></div><div class="score huge">${m.scoreA} <small>–</small> ${m.scoreB}</div></div><div class="pitch-teams"><team-box title="🇮🇹 SQUADRA A" team="A" m="${m.id}"></team-box><team-box title="🇧🇷 SQUADRA B" team="B" m="${m.id}"></team-box></div><div class="panel"><div class="toolbar"><h2>Statistiche per giocatore</h2><button class="btn primary" onclick="editMatchStats('${m.id}')">✎ Modifica statistiche</button></div>${matchStatsTable(m)}</div><div class="toolbar"><button class="btn" onclick="go('partite')">← Chiudi</button><button class="btn danger" onclick="deleteMatch('${m.id}')">Elimina partita</button></div>`)}
customElements.define('team-box',class extends HTMLElement{connectedCallback(){const m=db.matches.find(x=>x.id===this.getAttribute('m'));const t=this.getAttribute('team');this.innerHTML=`<div class="team ${t==='B'?'dark':''}"><h3>${this.getAttribute('title')}</h3><div class="field">${m.players.filter(x=>x.team===t).map(x=>`<div class="player"><b>${esc(x.name)}</b><span>⚽ ${x.g} · 🎯 ${x.a}</span></div>`).join('')||'<div class="empty">Nessun giocatore</div>'}</div></div>`}});
function matchStatsTable(m){return `<div class="table-wrap"><table class="table"><thead><tr><th>Giocatore</th><th>Squadra</th><th>Gol</th><th>Assist</th><th>Giallo</th><th>Rosso</th><th>Aut.</th><th>Rig.</th><th>Sub.</th><th>Cambio</th></tr></thead><tbody>${m.players.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.team}</td><td>${x.g}</td><td>${x.a}</td><td>${x.y}</td><td>${x.r}</td><td>${x.og}</td><td>${x.pen}</td><td>${x.sub}</td><td>${x.change?'✓':'—'}</td></tr>`).join('')}</tbody></table></div>`}
function editMatchStats(id){const m=db.matches.find(x=>x.id===id);app.innerHTML=layout('STATISTICHE PARTITA',`<form class="panel form" onsubmit="saveMatchStats(event,'${id}')">${m.players.map((x,i)=>`<div class="stat-edit"><b>${esc(x.name)}</b><span class="badge">Squadra ${x.team}</span><label>Gol<input name="g${i}" type="number" min="0" value="${x.g}"></label><label>Assist<input name="a${i}" type="number" min="0" value="${x.a}"></label><label>Gialli<input name="y${i}" type="number" min="0" value="${x.y}"></label><label>Rossi<input name="r${i}" type="number" min="0" value="${x.r}"></label><label>Autogol<input name="og${i}" type="number" min="0" value="${x.og}"></label><label>Rigori<input name="pen${i}" type="number" min="0" value="${x.pen}"></label><label>Subiti<input name="sub${i}" type="number" min="0" value="${x.sub}"></label><label class="check"><input name="ch${i}" type="checkbox" ${x.change?'checked':''}> Cambio</label></div>`).join('')}<div class="toolbar"><button type="button" class="btn" onclick="openMatch('${id}')">Annulla</button><button class="btn primary">Salva statistiche</button></div></form>`)}
function saveMatchStats(e,id){e.preventDefault();const m=db.matches.find(x=>x.id===id);m.players.forEach((x,i)=>{x.g=+e.target[`g${i}`].value||0;x.a=+e.target[`a${i}`].value||0;x.y=+e.target[`y${i}`].value||0;x.r=+e.target[`r${i}`].value||0;x.og=+e.target[`og${i}`].value||0;x.pen=+e.target[`pen${i}`].value||0;x.sub=+e.target[`sub${i}`].value||0;x.change=!!e.target[`ch${i}`].checked});save();openMatch(id)}
function deleteMatch(id){if(!confirm('Eliminare definitivamente questa partita?'))return;db.matches=db.matches.filter(x=>x.id!==id);db.ratings=db.ratings.filter(x=>x.matchId!==id);save();go('partite')}
function classifica(){const s=allStats().sort((a,b)=>b.g-a.g||b.a-a.a||b.app-a.app);app.innerHTML=layout('CLASSIFICA',`<div class="panel"><div class="toolbar"><h2>🏆 Classifica ${esc(db.season)}</h2><span class="muted">Ordinata per gol, assist, presenze</span></div>${statsTable(s)}</div><div class="panel"><h2>🏅 HALL OF FAME</h2><div class="cards"><div class="stat"><b>${s[0]?.p.name||'—'}</b><span>Capocannoniere</span></div><div class="stat"><b>${[...s].sort((a,b)=>b.a-a.a)[0]?.p.name||'—'}</b><span>Top assist</span></div><div class="stat"><b>${[...s].sort((a,b)=>b.app-a.app)[0]?.p.name||'—'}</b><span>Più presente</span></div><div class="stat"><b>${s.length?Math.max(...s.map(x=>x.app)):0}</b><span>Presenze max</span></div></div></div>`)}
function pagella(){const dates=[...new Map(db.matches.map(m=>[m.id,m])).values()];app.innerHTML=layout('PAGELLA',`<div class="panel"><div class="toolbar"><h2>🏅 Voti</h2><select id="ratingMatch" onchange="ratingForm(this.value)"><option value="">Seleziona partita</option>${dates.map(m=>`<option value="${m.id}">${esc(m.date)} · ${esc(m.format)} · ${m.scoreA}-${m.scoreB}</option>`).join('')}</select></div><div id="ratingArea" class="empty">Inserisci i voti della partita. Il voto più alto viene selezionato automaticamente.</div></div>`)}
function ratingForm(id){const m=db.matches.find(x=>x.id===id);if(!m)return;const old=Object.fromEntries(db.ratings.filter(r=>r.matchId===id).map(r=>[r.playerId,r.vote]));document.getElementById('ratingArea').innerHTML=`<form onsubmit="saveRatings(event,'${id}')"><div class="rating-grid">${m.players.map((p,i)=>`<label class="rating"><b>${esc(p.name)}</b><span>Squadra ${p.team}</span><input name="v${i}" type="number" min="0" max="10" step="0.1" value="${old[p.id]??''}" placeholder="—"></label>`).join('')}</div><p class="muted">⭐ Il voto più alto viene evidenziato automaticamente come migliore pagella della partita. Nessun MVP.</p><button class="btn primary">Salva voti</button></form>`}
function saveRatings(e,id){e.preventDefault();const m=db.matches.find(x=>x.id===id);db.ratings=db.ratings.filter(r=>r.matchId!==id);m.players.forEach((p,i)=>{const v=parseFloat(e.target[`v${i}`].value);if(!Number.isNaN(v))db.ratings.push({id:uid('r'),matchId:id,playerId:p.id,vote:v})});save();ratingForm(id);document.querySelectorAll('.rating input').forEach(inp=>{const vals=[...document.querySelectorAll('.rating input')].map(x=>parseFloat(x.value)).filter(Number.isFinite);if(vals.length&&parseFloat(inp.value)===Math.max(...vals))inp.closest('.rating').classList.add('best')})}
function ricordi(){app.innerHTML=layout('RICORDI',`<div class="toolbar"><span>Foto e ricordi della stagione</span><button class="btn primary" onclick="addMemory()">＋ Aggiungi</button></div><div class="memory-grid">${db.memories.map(x=>`<article class="memory"><div class="memory-placeholder">📸</div><h3>${esc(x.title)}</h3><span>${esc(x.date)}</span><p>${esc(x.text)}</p></article>`).join('')||'<div class="panel empty">Nessun ricordo caricato.</div>'}</div>`)}
function addMemory(){const title=prompt('Titolo del ricordo');if(!title)return;const text=prompt('Descrizione')||'';db.memories.push({id:uid('r'),title,text,date:new Date().toLocaleDateString('it-IT')});save();render('ricordi')}
function scheda(){app.innerHTML=layout('SCHEDA GIOCATORE',`<div class="panel"><select id="playerSelect" onchange="goPlayer(this.value)"><option value="">Seleziona giocatore</option>${db.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><div id="playerArea" class="empty">Seleziona un giocatore.</div></div>`)}
function goPlayer(id){if(!id)return;const x=allStats().find(z=>z.p.id===id);if(!x)return;app.innerHTML=layout('SCHEDA GIOCATORE',`<div class="panel profile"><div class="avatar">${esc(x.p.name.slice(0,1))}</div><h2>${esc(x.p.name)}</h2><span class="badge">${esc(x.p.role)}</span><span class="status ${x.p.injured?'injured':''}">${x.p.injured?'Infortunato':esc(x.p.status)}</span><div class="cards"><div class="stat"><b>${x.app}</b><span>Presenze</span></div><div class="stat"><b>${x.g}</b><span>Gol</span></div><div class="stat"><b>${x.a}</b><span>Assist</span></div><div class="stat"><b>${x.y+x.r}</b><span>Cartellini</span></div></div><button class="btn" onclick="go('scheda')">← Torna alla selezione</button></div>`)}
function giocatori(){app.innerHTML=layout('GESTIONE GIOCATORI',`<div class="toolbar"><span>${db.players.length} giocatori</span><button class="btn primary" onclick="playerForm()">＋ Nuovo giocatore</button></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Nome</th><th>Ruolo</th><th>Squadra</th><th>Quota</th><th>Pagata</th><th>Stato</th><th></th></tr></thead><tbody>${db.players.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.role)}</td><td>${esc(p.team||'—')}</td><td>€ ${(+p.admissionFee||0).toFixed(2)}</td><td>${p.paid?'✓':'—'}</td><td><span class="status ${p.injured?'injured':''}">${p.injured?'Infortunato':esc(p.status)}</span></td><td><button class="btn" onclick="playerForm('${p.id}')">Modifica</button></td></tr>`).join('')}</tbody></table></div>`)}
function playerForm(id=''){const p=db.players.find(x=>x.id===id)||{name:'',role:'Difensore',team:'',admissionFee:0,paid:false,injured:false,status:'Attivo',referee:false};app.innerHTML=layout(id?'MODIFICA GIOCATORE':'NUOVO GIOCATORE',`<form class="panel form" onsubmit="savePlayer(event,'${id}')"><div class="form-grid"><label>Nome<input name="name" required value="${esc(p.name)}"></label><label>Ruolo<select name="role">${ROLES.map(r=>`<option ${p.role===r?'selected':''}>${r}</option>`).join('')}</select></label><label>Squadra<input name="team" value="${esc(p.team)}"></label><label>Quota ammissione<input name="fee" type="number" min="0" step="0.01" value="${p.admissionFee||0}"></label><label>Stato<select name="status"><option ${p.status==='Attivo'?'selected':''}>Attivo</option><option ${p.status==='Inattivo'?'selected':''}>Inattivo</option></select></label></div><div class="checks"><label><input name="paid" type="checkbox" ${p.paid?'checked':''}> Quota pagata</label><label><input name="injured" type="checkbox" ${p.injured?'checked':''}> Infortunato</label><label><input name="referee" type="checkbox" ${p.referee?'checked':''}> Disponibile come arbitro</label></div><div class="toolbar"><button type="button" class="btn" onclick="go('giocatori')">Annulla</button><button class="btn primary">Salva giocatore</button></div></form>`)}
function savePlayer(e,id){e.preventDefault();const f=e.target;if(id){const p=db.players.find(x=>x.id===id);Object.assign(p,{name:f.name.value,role:f.role.value,team:f.team.value,admissionFee:+f.fee.value||0,paid:f.paid.checked,injured:f.injured.checked,status:f.status.value,referee:f.referee.checked})}else db.players.push({id:uid('p'),name:f.name.value,role:f.role.value,team:f.team.value,admissionFee:+f.fee.value||0,paid:f.paid.checked,injured:f.injured.checked,status:f.status.value,referee:f.referee.checked,registration:true,secondTeam:false,baseAverage:0,baseGoals:0,baseAssists:0,baseAppearances:0});save();go('giocatori')}
function regolamento(){app.innerHTML=layout('REGOLAMENTO',`<div class="panel"><div class="toolbar"><h2>📜 Regolamento ${esc(db.season)}</h2><button class="btn" onclick="editRules()">Modifica</button></div><div class="rules">${esc(db.rules||'Nessun regolamento inserito.').replace(/\n/g,'<br>')}</div></div>`)}
function editRules(){const r=prompt('Inserisci il regolamento:',db.rules||'');if(r===null)return;db.rules=r;save();render('regolamento')}
function luogo(){app.innerHTML=layout('LUOGO',`<div class="panel place"><h2>📍 Campo sportivo</h2><p>${esc(db.place)}</p><button class="btn primary" onclick="window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(db.place),'_blank')">Apri indicazioni</button><button class="btn" onclick="editPlace()">Modifica luogo</button></div>`)}
function editPlace(){const x=prompt('Indirizzo campo',db.place);if(x!==null){db.place=x;save();render('luogo')}}
function settings(){app.innerHTML=layout('SETTINGS',`<div class="panel"><h2>⚙️ Impostazioni</h2><div class="setting"><div><b>Modalità scura</b><small>Personalizza l'aspetto dell'app</small></div><input type="checkbox" ${db.settings.dark?'checked':''} onchange="toggleDark(this.checked)"></div><div class="setting"><div><b>Pagella</b><small>Abilita la gestione dei voti</small></div><input type="checkbox" ${db.settings.pagella?'checked':''} onchange="db.settings.pagella=this.checked;save();render('settings')"></div><div class="setting"><div><b>Stagione attiva</b><small>${esc(db.season)}</small></div></div><hr><button class="btn" onclick="exportData()">⬇ Esporta backup JSON</button><button class="btn" onclick="importData()">⬆ Importa backup JSON</button><button class="btn danger" onclick="resetSeason()">⚠ Reset stagione</button><p class="notice">I dati attuali vengono salvati nel browser. Il passaggio a un database online condiviso richiederà un backend dedicato.</p></div>`)}
function toggleDark(v){db.settings.dark=v;save();render('settings')}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='calcetto-manager-2026-27-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.players||!x.matches)throw Error();db=x;save();render('dashboard')}catch{alert('Backup non valido.')}};r.readAsText(i.files[0])};i.click()}
function resetSeason(){if(!confirm('ATTENZIONE: verranno cancellate tutte le partite, voti e ricordi della stagione. I giocatori resteranno. Continuare?'))return;db.matches=[];db.ratings=[];db.memories=[];save();render('dashboard')}
render(location.hash.slice(1)||'dashboard');