const pages=[['dashboard','📊 Dashboard'],['partite','⚽ Partite'],['classifica','🏆 Classifica'],['pagella','🏅 Pagella'],['ricordi','📸 Ricordi'],['scheda','🪪 Scheda Giocatore'],['giocatori','👤 Giocatori'],['regolamento','📜 Regolamento'],['luogo','📍 Luogo'],['settings','⚙️ Settings']];
const players=['Alberto','Alex Car.','Carlo','Cyr','Daniele','Fausto','Gabriele','Giovanni','Giulio','Loris','Matteo','Max','Mirko','Roberto','Tommaso','Lorenzo'];
const roles=['Portiere','Difensore','Centrocampista','Attaccante'];
const matches=[];
const nav=document.getElementById('nav'); const app=document.getElementById('app');
function renderNav(active){nav.innerHTML=pages.map(([id,label])=>`<button class="${id===active?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}
function go(id){history.pushState({},'',`#${id}`);render(id)} window.onpopstate=()=>render(location.hash.slice(1)||'dashboard');
function layout(title,body){return `<div class="wrap"><h1>${title}</h1>${body}</div>`}
function render(id){renderNav(id);({dashboard,partite,classifica,pagella,ricordi,scheda,giocatori,regolamento,luogo,settings}[id]||dashboard)()}
function dashboard(){app.innerHTML=layout('PANORAMICA',`<div class="toolbar"><span>Stagione: <b>2026/27</b></span><button class="btn">Aggiorna</button></div><div class="cards"><div class="stat"><b>${matches.length}</b><span>Partite</span></div><div class="stat"><b>${players.length}</b><span>Giocatori</span></div><div class="stat"><b>0</b><span>Gol totali</span></div><div class="stat"><b>0</b><span>Cartellini</span></div></div><div class="grid2" style="margin-top:12px"><div class="panel"><h2>⚽ Ultima partita</h2><div class="teams"><div class="team"><h3>🇮🇹 SQUADRA A</h3><div class="field"><div class="player">Nessuna partita</div></div></div><div class="team dark"><h3>🇧🇷 SQUADRA B</h3><div class="field"><div class="player">Nessuna partita</div></div></div></div></div><div class="panel"><h2>TOP SCORER WEEK</h2><div class="empty">Nessun dato per la nuova stagione</div></div></div><div class="panel"><h2>STATISTICHE SETTIMANALI</h2><table class="table"><thead><tr><th>Nome</th><th>Ruolo</th><th>Gol</th><th>Assist</th><th>Cart.</th><th>Aut.</th><th>Rig.</th><th>Partite</th></tr></thead><tbody>${players.slice(0,8).map((p,i)=>`<tr><td>${p}</td><td><span class="badge">${roles[i%4]}</span></td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>`).join('')}</tbody></table></div>`)}
function partite(){app.innerHTML=layout('PARTITE',`<div class="panel empty">Nessuna partita registrata nella stagione 2026/27.<br><br><button class="btn primary">+ Nuova partita</button></div>`)}
function classifica(){app.innerHTML=layout('CLASSIFICA',`<div class="panel"><div class="toolbar"><span>🏆 Classifica stagione 2026/27</span><button class="btn">Vista: Giocatori</button></div><table class="table"><thead><tr><th>#</th><th>Nome</th><th>Ruolo</th><th>Partite</th><th>Gol</th><th>Assist</th><th>Cartellini</th><th>Autogol</th><th>Rigori</th><th>Subiti</th><th>Con cambio</th></tr></thead><tbody>${players.map((p,i)=>`<tr><td>${i+1}</td><td><b>${p}</b></td><td><span class="badge">${roles[i%4]}</span></td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>`).join('')}</tbody></table></div><div class="panel"><h2>🏅 HALL OF FAME</h2><div class="cards"><div class="stat"><b>—</b><span>Capocannoniere</span></div><div class="stat"><b>—</b><span>Top assistman</span></div><div class="stat"><b>—</b><span>Miglior portiere</span></div><div class="stat"><b>—</b><span>Più presente</span></div></div></div>`)}
function pagella(){app.innerHTML=layout('PAGELLA',`<div class="panel"><div class="notice">La Pagella sarà disponibile dopo l'abilitazione da Impostazioni / Opzioni Admin.</div><div class="empty">Nessuna pagella per la nuova stagione.</div></div>`)}
function ricordi(){app.innerHTML=layout('RICORDI',`<div class="panel"><div class="empty">Nessun ricordo nella stagione 2026/27.<br><br><button class="btn primary">+ Aggiungi foto</button></div></div>`)}
function scheda(){app.innerHTML=layout('SCHEDA GIOCATORE',`<div class="panel"><div class="empty">👤<br><br>Seleziona un giocatore dalla dashboard.</div></div>`)}
function giocatori(){app.innerHTML=layout('GESTIONE GIOCATORI (ADMIN)',`<div class="panel"><div class="notice">Questa sezione è riservata agli admin.</div></div>`)}
function regolamento(){app.innerHTML=layout('REGOLAMENTO',`<div class="panel"><h2>Regolamento</h2><p>Sezione pronta per il regolamento della stagione 2026/27.</p></div>`)}
function luogo(){app.innerHTML=layout('LUOGO',`<div class="panel"><div class="empty">📍<br><br>Campo sportivo<br>Via Carreggia, 21010 Cardano al Campo VA<br><br><button class="btn primary">Indicazioni</button></div></div>`)}
function settings(){app.innerHTML=layout('SETTINGS',`<div class="panel"><h2>Impostazioni stagione</h2><p><b>Stagione attiva:</b> 2026/27</p><p><b>Modalità:</b> Nuova stagione, dati inizializzati a zero.</p></div>`)}
render(location.hash.slice(1)||'dashboard');
